name: "Create Release"
on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build and create release"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.3.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        id: checkout

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - name: do it
        id: doit
        run: |
          mkdir admin_ui_service
          cp -R dist/ admin_ui_service/
          zip -r admin_ui_service.zip admin_ui_service/
          echo "::set-output name=tag_name::$(node -p "require('./package.json').version")"
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.doit.outputs.tag_name }}
          release_name: admin_ui_service-${{ steps.doit.outputs.tag_name }}
          draft: false
          prerelease: false

      - name: Upload zip file
        id: upload-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./admin_ui_service.zip
          asset_name: admin_ui_service.zip
          asset_content_type: application/zip

